//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Synoris.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int ContactID { get; set; }
        public string ContactADDRESS { get; set; }
        public string SkypeID { get; set; }
        public string EmailID { get; set; }
        public string ContactPersonNo { get; set; }
        public string CompanyName { get; set; }
        public string ProjectTitle { get; set; }
    }
}
