//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Synoris.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public Department()
        {
            this.Payslips = new HashSet<Payslip>();
            this.Resources = new HashSet<Resource>();
        }
    
        public string DepartmentName { get; set; }
        public int DepartmentId { get; set; }
    
        public virtual ICollection<Payslip> Payslips { get; set; }
        public virtual ICollection<Resource> Resources { get; set; }
    }
}
