//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Synoris.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Interview
    {
        public int InterviewID { get; set; }
        public string CandidateName { get; set; }
        public string Phone { get; set; }
        public string JobForApply { get; set; }
        public string JobPortal { get; set; }
        public Nullable<System.DateTime> InterviewDate { get; set; }
        public string Time { get; set; }
        public Nullable<decimal> CurrentCTC { get; set; }
        public string Experience { get; set; }
        public string Feedback { get; set; }
    }
}
