//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Synoris.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payslip
    {
        public Nullable<int> ResourceID { get; set; }
        public string Paymonth { get; set; }
        public Nullable<int> Payyear { get; set; }
        public Nullable<int> TotalDays { get; set; }
        public Nullable<double> Daysworked { get; set; }
        public Nullable<int> TotalDaysforSalary { get; set; }
        public Nullable<int> Leave { get; set; }
        public Nullable<int> Basic_earnings { get; set; }
        public Nullable<int> Baisc_fixed { get; set; }
        public Nullable<int> provident_fund { get; set; }
        public Nullable<int> HouseRent_earning { get; set; }
        public Nullable<int> HouseRent_Fixed { get; set; }
        public Nullable<int> Esic { get; set; }
        public Nullable<int> Con_Allowance_earning { get; set; }
        public Nullable<int> Con_Allowance_fixed { get; set; }
        public Nullable<int> ProfessionalTax { get; set; }
        public Nullable<int> Incentive_earning { get; set; }
        public Nullable<int> Incentive_Fixed { get; set; }
        public Nullable<int> Tds { get; set; }
        public Nullable<int> OA1_earning { get; set; }
        public Nullable<int> OA1_fixed { get; set; }
        public Nullable<int> Lunch { get; set; }
        public Nullable<int> OA2_earning { get; set; }
        public Nullable<int> OA2_fixed { get; set; }
        public Nullable<int> Advanceloan { get; set; }
        public Nullable<int> OA3_earning { get; set; }
        public Nullable<int> OA3_fixed { get; set; }
        public Nullable<int> Specialperformance_earning { get; set; }
        public Nullable<int> Specialperformance_Fixed { get; set; }
        public Nullable<int> Grosspay_earning { get; set; }
        public Nullable<int> Grosspay_fixed { get; set; }
        public Nullable<int> Totaldeduction { get; set; }
        public Nullable<int> Netpay { get; set; }
        public Nullable<System.DateTime> Date1 { get; set; }
        public int PayslipID { get; set; }
        public Nullable<int> DepartmentId { get; set; }
    
        public virtual Department Department { get; set; }
    }
}
