//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Synoris.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectResource
    {
        public int ProjectResourceID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<int> ResourceID { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> AssignDate { get; set; }
        public string AssignBy { get; set; }
    
        public virtual Resource Resource { get; set; }
    }
}
